### ISSUE TITLE
upgrade to sweetalert2 because input

### ISSUE THREAD

**Issue by bsssp** [oitozero/ngSweetAlert#58]
http://limonte.github.io/sweetalert2/

**Comment by limonte** [comment]
Hi @oitozero, I'm the author of sweetalert2.

Original plugin is currently inactive and unsupported. Sweetalert2 is far ahead and it has a ton of additional cool features, as inputs types, modals chaining etc. 

Swal2 also has several active contributors and most probably it won't be dead as original swal.

For ngSweetAlert transition from swal to swal2 should be pretty easy, I'm available for any help.

The only one big difference is using Promises instead of callbacks (yeah, it's 2016 now :smile:): https://github.com/sweetalert2/sweetalert2/releases/tag/v1.0.0

**Comment by oitozero** [comment]
@limonte Just added you as collaborator. Please let m know what you need from me, if anything. Thx

**Comment by marcodussin** [comment]
thankyou limonte!
