### ISSUE TITLE
Fix the version of sweetalert

### ISSUE THREAD

**Issue by harshavardhan-reddy** [oitozero/ngSweetAlert#78]
Can you fix the version of sweetalert to 1.1.3.
The newest version of sweetalert is breaking the ng-sweet-alert

**Comment by CaporalDead** [comment]
:+1: I'm getting the same issue, I had to fix sweetalert to 1.1.3.

**Comment by emrealparslan93** [comment]
Same here.

**Comment by emrealparslan93** [comment]
What is the solution? I tried to change "angular-sweetalert": "~1.1.3" in bower.json but it didn't help. @harshavardhan-reddy @CaporalDead

**Comment by harshavardhan-reddy** [comment]
@emrealparslan93  Yes you need to install sweetalert manually (1.1.3). This will override the sweetalert installed by ngSweetAlert.

**Comment by carlosafonso** [comment]
You can also modify your `bower.json` to point to our forked repository:

```
{
    "angular-sweetalert": "git@github.com:theviralab/ngSweetAlert.git#c0b746e"
}
```

This installs the correct version of SweetAlert. This is a temporary solution until PR #79 gets merged.

**Comment by ricky300300** [comment]
Fix this issue please, yesterday I wasted my 2-3 hr and found then this issue

**Comment by carlosafonso** [comment]
Thank you @oitozero  for merging #79 .

It seems that declaring the dependency as follows:

```json
{
    "angular-sweetalert": "latest"
}
```

Still does not work, since if I'm not mistaken `latest` points to the most recent tagged release (which in this case still contains the old version of bower.json).

Pointing to `master` instead of `latest` fixes this. Also, creating a new release should solve this as well.

**Comment by Srounsroun** [comment]
#83 can fix the issue
